name: example-inigo-action
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  inigo:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Inigo CLI
        run: wget -c https://github.com/inigolabs/artifacts/releases/latest/download/cli_linux_amd64.tar.gz -O - | tar -xz;

      - name: CLI login
        env:
          INIGO_USERNAME: ${{ secrets.INIGO_USERNAME }}
          INIGO_PASSWORD: ${{ secrets.INIGO_PASSWORD }}
        run: ./inigo login
